services:
  fileshare:
    build: .
    container_name: fileshare_c
    restart: unless-stopped
    volumes:
      - "./data:/app/data"
    labels:
      - "traefik.http.routers.fileshare.rule=Host(`localhost`)"
  reverse-proxy:
    image: traefik
    container_name: traefik_c
    restart: unless-stopped
    depends_on:
      - fileshare
    command:
      - "--providers.docker"
    ports:
      - 3000:80
    volumes:
      - "/run/user/1000/docker.sock:/var/run/docker.sock:ro"
